#!/usr/bin/env bash

set -u			# treat unset variables as an error when substituting
me=$( basename $0 )

function usage {
	cat << EOT

SYNOPSIS                          ($0)
    $me - register object at EZID and deposit in the Internet Archive

USAGE
    $me [ -c Collection ] Subcommand

DESCRIPTION

See the ./ia script at the very end of this file!


SUBCOMMANDS
--- Possible vision, NOT WORKING ---
upload Identifier MetadataYAML Policy File ...
remove Identifier
list Identifier

The Identifier is ...
The MetadataYAML file is ...
The Policy string is ...
EOT
}

cmd=${1:-}	; shift

[[ ! "$cmd" ]] && {
	usage
	exit
}

case $cmd in

upload)
	id=${1:-}	; shift
	mdfile=${1:-}	; shift
	policy=${1:-}	; shift
	[[ "$id" && "$mdfile" && "$policy" ]] || {
		echo "Error: upload needs identifier, metadata, and policy" 1>&2
		exit 1
	}
	files=( $@ )
	#for i in ${files[@]}
	#do echo i is $i
	#done
	echo cmd is $cmd
	exit
	;;
remove)
	echo cmd is $cmd
	exit
	;;
list)
	echo cmd is $cmd
	exit
	;;
*)
	echo Error: unknown command: $cmd 1>&2
	usage
	exit 1
	;;
esac

exit

# First, you'll have set up a ~/.config/ia.ini file by running "./ia configure"

#./ia upload myidjakkbl2 testia.txt --metadata="foo:bar" --metadata="collection:luck" && echo ok

version=0
ia_item="ark_13030_c7xk84q2j"
filebase="cdl_ebi_prefixes.yaml"
target="https://archive.org/download/$ia_item/$filebase"
n2t_item="ark:/13030/c7xk84q2j"

# upload item file options, where
#  $item = object = identifier
#  file = filename to add

# All filenames end up accessible under stable IA "archival URL":
#    https://archive.org/download/<identifier>/<filename>
# SPT on https://archive.org/download/ark:/13030/c7xk84q2j/cdl_ebi_prefixes.yaml
# once: upload $ia_item $filebase
#       $n2t_item.set _t $target
# first time: snag --mknextcopy $filebase
#       upload $ia_item $filebase.v1
#       SPT permits n2t.net/$n2t_item.v1 -> $target.v1
# second time: upload $filebase.v2
# ...

xxx add this for each snapshot!
   --metadata="bestest:https://n2t.net/$n2t_item" \

./ia upload "$item" "filename.v$version" \
   --metadata="collection:luck" \
   --metadata="creator:California Digital Library and European Bioinformatics Institute" \
   --metadata="title:Registry of prefixes (namespaces) supported by identifiers.org and n2t.net" \
   --metadata="date:2017-09-25" \
   --metadata="subject:identifier" \
   --metadata="subject:resolver" \
   --metadata="subject:scheme" \


