# n2t crontab file -- macbook version

MAILTO=jak@ucop.edu

#20,50 9-21 * * * if [ -e /Users/jak/shoulders/ok ]; then open /Users/jak/shoulders; fi

# Look once a night for rotated transaction_log files to rename.
# Note that such files are generally created only once a week.
#
15 00 * * 1-7 bash -lc "admegn logrename | grep -v ^nothing"

#### Sundays at 4:03 am, delete log files older than 6 months.
03 04 * * 0 bash -lc "admegn logdelete 6" >> logs/logdelete_log 2>&1

